services:

  nginx:
    image: nginx:latest

  postgresql:
    image: postgres:alpine3.16

  mongo:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2

  ai.project:
    image: ${DOCKER_REGISTRY-}ai-project:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: .
      dockerfile: ai-project/Dockerfile
  
#network section
networks:
  default:
    name: ai-project
    driver: bridge
  
#volume
volumes:
  nginx_data:
    name: nginx_data
  postgres_data:
    name: postgres_data
  portainer_data:
    name: portainer_data
  elasticsearch_data:
    name: elasticsearch_data
  mongo_data:
    name: mongo_data